### ISSUE TITLE
Add constraints for `content.frontmatter` block

### ISSUE THREAD

**Issue by traut** [blackstork-io/fabric#116]
## Background

At the moment, `content.frontmatter` blocks in FCL is rendered as a "normal" content block and while it was easy to implement, it is an incorrect behavior. Fabric should implement custom logic for evaluating / rendering `content.frontmatter` blocks.

## Design

- add constraints for `content.frontmatter` blocks:
    - `content.frontmatter` blocks can only be defined on the root level of the `document` block
    - only one `content.frontmatter` block can be defined in the document
- during evaluation, `content.frontmatter` is placed at the very top of the document -- before any other content output. It doesn't mean that the fontmatter block should be evaluated first, just that the output must be at the beginning of the document.

For example,

```hcl

document "test" {

  title = "Test Title"

  content text {
    text = "Normal text"
  }

  content frontmatter "foo" {
    content = {
      fieldA = "valueA",
      fieldB = "valueB",
    }
  }
}
```

produces the output:

```markdown
---
fieldA: valueA
fieldB: valueB
---

# Test Title

Normal text
```

**Comment by dobarx** [comment]
@traut Maybe it also needs `format`? Usually frontmatter in markdown can be `yaml`, `toml` or `json`

**Comment by dobarx** [comment]
Ahh, forgot I already did that 😄

**Comment by traut** [comment]
oh, that's neat! We can start with a simple enum that supports only `doc-start` (beginning of the document) and `as-defined` (where the block is defined), and rename / extend when needed

**Comment by dobarx** [comment]
@traut 
I think latest changes cover part of this issue. It places frontmatter always on top of the rendered document. Two things remain:
- > only one content.frontmatter block can be defined in the document 

  This can be easaly checked now on plugin level, since we have content tree and info which plugin owns which content. I can throw error if second frontmatter is detected.

- > blocks can only be defined on the root level of the document block

  This can also be checked on plugin level using content tree. I can throw an error if `content frontmatter` is detected in `section`.
